### ISSUE TITLE
row 18446744073709551574 is out of range

### ISSUE THREAD

**Issue by tobwen** [isciences/exactextractr#1]
When trying to run *partial_mask*, I'm getting this error for whatever raster and vector data I'm trying to use:
`Error in CPP_weights(as.vector(raster::extent(x)), raster::res(x), wkb) : 
  Row 18446744073709551574 is out of range.`

I've created this stripped down example the reproduce the problem:

1. Create an empty raster with a resolution of 100 x 100 meters and fake some values
```
r <- raster(xmn=391030, xmx=419780, ymn=5520000, ymx=5547400)
res(r) = c(100, 100)
crs(r) <- CRS('+init=EPSG:25832')
values(r) <- 1:ncell(r)
```

2. Load polygons (rename the attached [polygons.txt](https://github.com/isciences/exactextractr/files/2121509/polygons.txt) to *polygons.geojson*)
`p <- st_read("polygons.geojson", crs = 25832)`

3. Execute *partial_mask*
`partial_mask(r, p)`

I'm running R version 3.4.3 (2017-11-30) on Windows 7, 64-bit.

**Comment by dbaston** [comment]
Thanks @tobwen for a clear and reproducible report. I'll have a fix up shortly.

**Comment by tobwen** [comment]
@dbaston Recompiled, tested, working! :thumbsup:

Maybe I should create a PR with a nicer bbox and polygon :wink:
