### ISSUE TITLE
Simpler area-based weighting for rasters in geographic coordinates

### ISSUE THREAD

**Issue by dbaston** [isciences/exactextractr#15]
It should be possible to use a flag to specify area-based weighting for rasters in geographic coordinates, rather than having to construct an input stack with previously-computed areas.

**Comment by helsharif** [comment]
Yes this enhancement would be greatly appreciated!

**Comment by dbaston** [comment]
I think this is sufficiently simplified by the ability to use weighting rasters with R summary functions, e.g., `exact_extract(prec, brazil, function(x, cov, wt) weighted.mean(x, cov * wt), weights = area(prec))`. At least, I'm doubtful that adding additional syntax would simplify a function that already has too many ways of calling it.
