### ISSUE TITLE
sfc_GEOMETRY not accomodated

### ISSUE THREAD

**Issue by axlehner** [isciences/exactextractr#20]
Hi, when the class of the geometry is sfc_GEOMETRY instead of (MULTI)POLYGON (in your vignette example it is a multipolygon), the function fails with error message

```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘exact_extract’ for signature ‘"RasterLayer", "sfc_GEOMETRY"’
```

**Comment by dbaston** [comment]
I'm not sure how to support `GEOMETRY`, because sf doesn't provide seem to provide a method to serialize `sfc_geometry` to WKB. Can you describe the use case a bit? Where is your `sfc_GEOMETRY` coming from?
