### ISSUE TITLE
submitted sf will break exactextractr on CRAN

### ISSUE THREAD

**Issue by edzer** [isciences/exactextractr#24]
With new sf, we see
```r
st_crs("+proj=longlat +datum=WGS84 +no_defs")$epsg
```
resulting in NA rather than 4326. This is GDAL, trying to guess the epsg from the WKT representation of the proj4string. I think this is wrong, but cannot be resolved by sf. In any case, it causes errors in your tests, and errors on CRAN once sf gets accepted. See https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200319_213604/reverseDependencies/summary.txt and https://www.r-spatial.org/r/2020/03/17/wkt.html

**Comment by dbaston** [comment]
Many thanks @edzer for the report and analysis.
