### ISSUE TITLE
Parse Exception ERROR, Unknown WKB type 235

### ISSUE THREAD

**Issue by danielreispereira** [isciences/exactextractr#26]
I'm getting the following error when trying to get the coverage fraction from a .kml that has multiple holes in it  (multipolygon?). 
Same code works fine if the kml is simple (no holes in the middle).

Since I have no idea what the error means: what should I try first? Redraw the KML ?

```
> cov_frac <- coverage_fraction(x = rast, y = poly, crop=TRUE)
**Error in CPP_coverage_fraction(x, wkb, crop) :   ParseException: Unknown WKB type 235**
```

![GithubExample](https://user-images.githubusercontent.com/4158858/78579992-23910700-7808-11ea-897b-70c1d6f6ae54.jpg)

**Comment by dbaston** [comment]
Can you share the KML?

**Comment by danielreispereira** [comment]
Sure thing. Attached. 
[kmlExample_Baston_Github_.kml.txt](https://github.com/isciences/exactextractr/files/4440128/kmlExample_Baston_Github_.kml.txt)

**Comment by dbaston** [comment]
Works with the raster I'm using. Can you share the extent and resolution of yours?

**Comment by danielreispereira** [comment]
Hmm. 
I'm using the raster attached. CHIRPS rainfall from: [https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_daily/tifs/p05/](url).

```
class      : RasterLayer 
dimensions : 2000, 7200, 14400000  (nrow, ncol, ncell)
resolution : 0.05, 0.05  (x, y)
```

[rasterTEST.tif.txt](https://github.com/isciences/exactextractr/files/4440982/rasterTEST.tif.txt)

**Comment by dbaston** [comment]
Here's what I'm running:

```
library(raster)
library(sf)
library(exactextractr)

prec <- raster('chirps-v2.0.2020.02.29.tif')
poly <- st_read('test.kml')

cf <- coverage_fraction(prec, poly, crop=TRUE)[[1]]

plot(cf)
plot(st_geometry(poly), add=TRUE)
```

![image](https://user-images.githubusercontent.com/6318931/78609767-67e4cd00-7831-11ea-8343-bbcd9e7f6585.png)

**Comment by danielreispereira** [comment]
Interesting.  I keep getting the same error:

![image](https://user-images.githubusercontent.com/4158858/78655247-1d4c6a80-789c-11ea-8a79-8a358a811549.png)

Pkg version, windows dependencies maybe?

**Comment by dbaston** [comment]
Interesting. I assume you have the latest exactextractr and sf from CRAN. I'll try to reproduce on a Windows machine.

I suspect this is somehow related to the third dimension, in which case a workaround would be `coverage_fraction(prec, st_zm(poly), crop=TRUE)` .

**Comment by danielreispereira** [comment]
That does the trick. What should have I noticed that I missed in this case? KMLs with 3 dimensions ?

**Comment by dbaston** [comment]
I don't think you missed anything. Ideally the Z dimension would just be ignored, and I'm not sure why this appears to happen on one platform but not another. I'll keep this issue open until I have time to look into it.

**Comment by danielreispereira** [comment]
Thanks for the fix
