### ISSUE TITLE
Possibility to add additional Statistics

### ISSUE THREAD

**Issue by lbusett** [isciences/exactextractr#30]
Hi, 

    thanks for this: really helpful and fast!

Since I am in the process of "switching" my "R" packages to usage of exact_extractr (abandoning velox, or "standard" raster::extract): would it be possible/useful to include additional statistic indicators, such as variance/standard deviation/variation coefficient ? I know I can extract all "pixel" values and then compute them myself, but I think having them ready-made could be useful.

HTH,

   Lorenzo

**Comment by dbaston** [comment]
I've gone ahead and implemented population value for consistency with ArcGIS and QGIS. I'll wait for someone to request the others if there's an application for them.

**Comment by lbusett** [comment]
Thanks!
