### ISSUE TITLE
"count" as summary

### ISSUE THREAD

**Issue by chljl** [isciences/exactextractr#39]
Can you give an example of using "count" as the summary operation. I'm not sure what the correct grammar is. 
exact_extract(rast, poly,'count', const), where const the the cell value I want to count? Also, what if I want to count cells with the value large than a given value?

**Comment by dbaston** [comment]
`count` counts all of the pixels, regardless of their value. If you want to count cells with a value larger than a given value you can use a custom function, like `function(value, coverage_fraction) sum(coverage_fraction[value > threshold])`

**Comment by chljl** [comment]
Thanks a lot. That works. The manual says "count- the sum of fractions of raster cells with defined values covered by the polygon“. I thought it means that count can accept user defined values.

**Comment by chljl** [comment]
It looks like I didn't get it work correctly. I am trying to extract area fraction of polygons where land cover type equals to forest. Here is what I use: exact_extract(LULC, bound1, function(value, coverage_fraction) sum(coverage_fraction[value = 41])). LULC is my land cover raster, bound1 is my polygons. I am trying to extract the area of raster value =41 and calculate its total percentage in each polygon.  My results are mostly 0 or 1, which are not as expected. Anything I did wrong?
