### ISSUE TITLE
Not working for large files

### ISSUE THREAD

**Issue by pnsinha** [isciences/exactextractr#4]
I tried the library for the first time. 
Zonal stat on Brazil raster file (resolution 100meters) with 310896 polygons.

Error in CPP_stats(x, wkb, fun) : 
  Evaluation error: long vectors not supported yet: memory.c:3486.

**Comment by dbaston** [comment]
Thanks for the report, @pnsinha . Can you share your inputs, or describe how large the largest polygon is?
