### ISSUE TITLE
citation?

### ISSUE THREAD

**Issue by mikejohnson51** [isciences/exactextractr#42]
This is a hugely valuable library. Is there a preferred citation for those using in for peer-review papers?

Thanks for the great work!

Mike

**Comment by dbaston** [comment]
Thank you! I think the default output of `citation('exactextractr')` is fine:

```
> citation('exactextractr')

To cite package ‘exactextractr’ in publications use:

  Daniel Baston (2020). exactextractr: Fast Extraction from Raster Datasets using Polygons. R package version 0.5.0.
  https://CRAN.R-project.org/package=exactextractr

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {exactextractr: Fast Extraction from Raster Datasets using Polygons},
    author = {{Daniel Baston}},
    year = {2020},
    note = {R package version 0.5.0},
    url = {https://CRAN.R-project.org/package=exactextractr},
  }
```

**Comment by mikejohnson51** [comment]
Awesome, thanks @dbaston!

**Comment by szylinski-sa** [comment]
I've noticed that the author field includes {{ }}, which results in citations printed with the name as-is "Daniel Baston 2020" rather than the standard "Baston 2020" that results from single { }. Is that intended?
