### ISSUE TITLE
Output Order

### ISSUE THREAD

**Issue by r-barnes** [isciences/exactextractr#43]
I've been looking for a way to easily join the outputs of this processing back to the input shapefile.

If the output is in the same order as the polygons in the shapefile, then the solution is simple, but I don't see a guarantee or explanation of the ordering in the documentation.

Could you clarify what the output ordering is?

**Comment by dbaston** [comment]
The output ordering is the same as the input, so you can `cbind` the results to the input. Alternatively, you can include columns from the input directly in the output, using `append_cols`.

**Comment by r-barnes** [comment]
Thanks, that's very helpful!
