### ISSUE TITLE
Inability to deal with null (NA) values.

### ISSUE THREAD

**Issue by CCapinha** [isciences/exactextractr#5]
Hi,
everything works great (incredibly fast!). However, when a polygon zone encloses a few NA values the result of the function returns NA. Could not find a way to bypass this on the function code. 
Cheers,
César

**Comment by dbaston** [comment]
Hi @CCapinha ,
I added some tests showing behavior with NA values here: https://github.com/isciences/exactextractr/blob/master/tests/testthat/test_exact_extract.R#L57

Do you need to pass `na.rm = TRUE` to the function you're using? (see line 83 in the test file)

If this doesn't resolve the issue, can you please post the code (and if possible, the data) that you're using?

**Comment by CCapinha** [comment]
Hi Dan,
Yes, na.rm = TRUE, solves the problem.
Once again, it's impressive how fast the computation is made.
Many thanks for this cool addition to the R universe.
Cheers
Cesar


Em 18/12/2018 a 4:24 da tarde, <Dan Baston<mailto:notifications@github.com>> escrevi:


Hi @CCapinha<https://github.com/CCapinha> ,
I added some tests showing behavior with NA values here: https://github.com/isciences/exactextractr/blob/master/tests/testthat/test_exact_extract.R#L57

Do you need to pass na.rm = TRUE to the function you're using? (see line 83 in the test file)

If this doesn't resolve the issue, can you please post the code (and if possible, the data) that you're using?

**Comment by dbaston** [comment]
Great, glad to hear this fixed it.
