### ISSUE TITLE
Summarizing categorical data

### ISSUE THREAD

**Issue by RS-eco** [isciences/exactextractr#50]
Hello,

I tried to use the summarize_df=T feature in the exact_extract() function, but using your own examples from within the package vignettes:

```
landcov_fracs <- exact_extract(clc, concelhos, function(df) {
    df %>%
      mutate(frac_total = coverage_fraction / sum(coverage_fraction)) %>%
      group_by(name, value) %>%
      summarize(freq = sum(frac_total))
  }, summarize_df = TRUE, include_cols = 'name', progress = FALSE)
```
I get the following error:

> Error in .exact_extract(x, y, fun = fun, ..., include_xy = include_xy,  : 
>   exact_extract was called with a function that does not appear to be of the form `function(values, coverage_fractions, ...)`

I have updated all my R packages, am using R version 4.0.4 and have just installed the recent package version from Github.

**Comment by RS-eco** [comment]
Hm, I used `github_install("isciences(exaczextractr")` and it says I have version 0.6.0 installed, which I believe to be the current version. I have just de-installed and re-installed the package again and I still get the same error message.

**Comment by dbaston** [comment]
Closing this issue as version 0.6.0 has been released and the vignettes are built correctly by CRAN.
