### ISSUE TITLE
Dev version has no help file?

### ISSUE THREAD

**Issue by MatthieuStigler** [isciences/exactextractr#72]
It looks like there is a problem with the documentation in the DEV version? I cannot access it :-(

Thanks!

``` r
devtools::install_github("isciences/exactextractr")
#> Skipping install of 'exactextractr' from a github remote, the SHA1 (648eb445) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(exactextractr)
packageVersion("exactextractr")
#> [1] '0.8.0'
help(exact_extract)
#> No documentation for 'exact_extract' in specified packages and libraries:
#> you could try '??exact_extract'
```

<sup>Created on 2022-02-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dbaston** [comment]
I don't commit the generated `Rd` files to the repo, and as far as I know `devtools` still does not provide an option to generate them with `install_github`. So I think the only options are to clone the repository and build/install locally, or view the documentation at https://isciences.gitlab.io/exactextractr/reference/index.html.

**Comment by MatthieuStigler** [comment]
I see, thanks for the fast answer!

And out of curiosity, why don't you also commit the Rd files?

**Comment by dbaston** [comment]
I keep generated files out of the repo to reduce merge conflicts and history noise from different versions of roxygen producing different output.
