### ISSUE TITLE
Looking for Python version of exactextract

### ISSUE THREAD

**Issue by YeechingTiger** [isciences/exactextractr#76]
Hi, I could not find a Python library that has compatible accuracy as your excellent job. Is there any experiment branch for a Python version of exactextract?

**Comment by dbaston** [comment]
No, but there is a command-line tool that provides some of the functionality outside of R: https://github.com/isciences/exactextract

**Comment by mdsumner** [comment]
look at this recent blogpost

https://discourse.pangeo.io/t/conservative-region-aggregation-with-xarray-geopandas-and-sparse/2715

**Comment by dbaston** [comment]
Related: https://github.com/isciences/exactextract/issues/7 and https://github.com/isciences/exactextract/pull/34
