### ISSUE TITLE
Timeline on 0.9.0 to CRAN?

### ISSUE THREAD

**Issue by kpmessier** [isciences/exactextractr#85]
I'm wondering what your timeline for pushing version 0.9.0 to CRAN is? In particular, I'm interested in the "frac" function of exact_extract. I've implemented a version of the data.frame operations you outline in the "summarizing categorical data" article (https://isciences.gitlab.io/exactextractr/articles/vig2_categorical.html); however, compared to the supported summary operations, it is much slower. I suspect the updated version in 0.9.0 with 'frac' is on par with the other summary functions. Thanks!

**Comment by dbaston** [comment]
Thanks for the reminder! I submitted it a few weeks ago but it was rejected because a site linked to in the README was down. I will try resubmitting now.

I'll be interested to hear your feedback on `frac`. I haven't done much performance testing on it.

**Comment by dbaston** [comment]
Released: https://cran.r-project.org/web/packages/exactextractr/index.html
