### ISSUE TITLE
Error during install using devtools on Windows machine

### ISSUE THREAD

**Issue by laceymason** [isciences/exactextractr#9]
I keep getting the error below when trying to install this package on my Windows machine.  I have installed the rgeos and devtools packages.  Any advice is appreciated!

`> install_github('isciences/exactextractr')
Downloading GitHub repo isciences/exactextractr@master
  
  
  
   checking for file 'C:\Users\masonl\AppData\Local\Temp\1\RtmpSwJxKY\remotes8943ce5204\isciences-exactextractr-37c2f0f/DESCRIPTION' ...
  
   checking for file 'C:\Users\masonl\AppData\Local\Temp\1\RtmpSwJxKY\remotes8943ce5204\isciences-exactextractr-37c2f0f/DESCRIPTION' ... 
  
√  checking for file 'C:\Users\masonl\AppData\Local\Temp\1\RtmpSwJxKY\remotes8943ce5204\isciences-exactextractr-37c2f0f/DESCRIPTION' (642ms)

  
  
  
-  preparing 'exactextractr': (658ms)

  
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
√  checking DESCRIPTION meta-information
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (1.2s)  
-  checking for empty or unneeded directories (413ms)
-  building 'exactextractr_0.1.0.tar.gz'

  
Warning:
   Warning: file 'exactextractr/cleanup' did not have execute permissions: corrected

  
Warning:
  
   Warning: file 'exactextractr/configure' did not have execute permissions: corrected

  
   

* installing *source* package 'exactextractr' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs

*** arch - i386
rm -f exactextractr.dll RcppExports.o exact_extract.o exactextract/src/cell.o exactextract/src/geos_utils.o exactextract/src/floodfill.o exactextract/src/box.o exactextract/src/area.o exactextract/src/side.o exactextract/src/traversal_areas.o exactextract/src/extent.o exactextract/src/perimeter_distance.o exactextract/src/traversal.o exactextract/src/raster_cell_intersection.o exactextract/src/coordinate.o
mkdir -p ../inst
"C:/Users/masonl/DOCUME~1/R/R-35~1.2/bin/i386/Rscript.exe" --vanilla "../tools/winlibs.R" 2.2.3
trying URL 'https://github.com/rwinlib/gdal2/archive/v2.2.3.zip'
Content type 'application/zip' length 44034709 bytes (42.0 MB)
==================================================
downloaded 42.0 MB

C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exact_extract.cpp -o exact_extract.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exactextract/src/cell.cpp -o exactextract/src/cell.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exactextract/src/geos_utils.cpp -o exactextract/src/geos_utils.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exactextract/src/floodfill.cpp -o exactextract/src/floodfill.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exactextract/src/box.cpp -o exactextract/src/box.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exactextract/src/area.cpp -o exactextract/src/area.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exactextract/src/side.cpp -o exactextract/src/side.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exactextract/src/traversal_areas.cpp -o exactextract/src/traversal_areas.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exactextract/src/extent.cpp -o exactextract/src/extent.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exactextract/src/perimeter_distance.cpp -o exactextract/src/perimeter_distance.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exactextract/src/traversal.cpp -o exactextract/src/traversal.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exactextract/src/raster_cell_intersection.cpp -o exactextract/src/raster_cell_intersection.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/Users/masonl/DOCUME~1/R/R-35~1.2/include" -DNDEBUG  -I"C:/Users/masonl/Documents/R/R-3.5.2/library/Rcpp/include"     -std=c++14 -I../windows/gdal2-2.2.3/include/geos   -O2 -Wall  -mtune=generic -c exactextract/src/coordinate.cpp -o exactextract/src/coordinate.o
C:/RBuildTools/3.5/mingw_32/bin/g++ -shared -s -static-libgcc -o exactextractr.dll tmp.def RcppExports.o exact_extract.o exactextract/src/cell.o exactextract/src/geos_utils.o exactextract/src/floodfill.o exactextract/src/box.o exactextract/src/area.o exactextract/src/side.o exactextract/src/traversal_areas.o exactextract/src/extent.o exactextract/src/perimeter_distance.o exactextract/src/traversal.o exactextract/src/raster_cell_intersection.o exactextract/src/coordinate.o -lgeos_c -lgeos -L../windows/gdal2-2.2.3/lib-4.9.3/i386 -LC:/Users/masonl/DOCUME~1/R/R-35~1.2/bin/i386 -lR
C:/RBuildTools/3.5/mingw_32/bin/../lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lgeos_c
C:/RBuildTools/3.5/mingw_32/bin/../lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lgeos
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'exactextractr'
* removing 'C:/Users/masonl/Documents/R/R-3.5.2/library/exactextractr'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/masonl/AppData/Local/Temp/1/RtmpSwJxKY/file8946682340/exactextractr_0.1.0.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
`

**Comment by dbaston** [comment]
Thank you  for the report. I've updated `exactextractr` with a fix in 44bc2690f248bc8bcb.

**Comment by laceymason** [comment]
Thank you!
