### ISSUE TITLE
Error: [crop] incorrect number of values (too many) for writing

### ISSUE THREAD

**Issue by mjdcurtis** [isciences/exactextractr#97]
Tried to extract a big ascii raster with max_cells_in_memory = 200000000L and got this message:

Error: [crop] incorrect number of values (too many) for writing

(If I use a smaller value of max_cells_in_memory, I get:

Cannot preload entire working area of 174974720 cells with max_cells_in_memory = 50000000. Raster values will be read for each feature individually, which is very slow.)

**Comment by dbaston** [comment]
This error is coming from terra. Apparently it is trying to write the cropped raster to disk, which even if successful would defeat the purpose of preloading it.

Can you try increasing the memory available to terra to see if this goes away?
https://rspatial.github.io/terra/reference/terraOptions.html
